apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycustomresources.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
  names:
    plural: mycustomresources
    singular: mycustomresource
    kind: MyCustomResource