apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pubsub
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pubsub-namespace
  source:
    repoURL: 'https://gitlab.com/codeway-devops/neslihan/Questions/-/tree/main/Question-2?ref_type=heads'
    path: /app
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true